### ISSUE TITLE
Problem previewing content locally

### ISSUE THREAD

**Issue by stephenturvey** [the-open-university/student-theme-framework#10]
The localhost preview (dr jekyll?) doesn't update immediately. For example if I edit the style sheet then go to Chrome to view the change, sometimes it takes about 5 refreshes before it loads it. This is quite a big issue for me because I'm constantly making small updates to things like padding, and I might be moving things left or right by 1 pixel, and so at the moment I can't be sure I'm viewing the latest version. Can anything be done? @guyweb @sleicester

**Comment by sleicester** [comment]
This issue was moved to the-open-university/ouice#10
