### ISSUE TITLE
Alternative solution for the example site

### ISSUE THREAD

**Issue by guyweb** [the-open-university/student-theme-framework#11]
Wondering if we should simplify the example site so that it is a single index page that acts as a springboard to examples? That way we could use 100% of available canvas for the example and not have to worry about maintaining menus and other consistent interface on every page. And example being a page that shows an example breadcrumb. At the moment that page has two breadcrumbs on it - the example and the breadcrumb in the template. If we did it this alternative way we would have one breadcrumb and the user could click 'back' on the browser to go back to other examples.

**Comment by sleicester** [comment]
We can also bring in really good search with Algolia, I think they have a free document search for public sites.

I'm wondering if we have a simple Laravel app that pulls in the framework, but has a way of organising the code examples that we can loop through and automatically create the pages etc. Together with the ability to copy the code.

I'm also wondering if different bits could be tagged against multiple sections. We might have to look at this soon as the framework gets adopted and used. This will be important as a style guide as well.

**Comment by sleicester** [comment]
This issue was moved to the-open-university/ouice#11
