### ISSUE TITLE
Merge Drupal specifics into main framework

### ISSUE THREAD

**Issue by guyweb** [the-open-university/student-theme-framework#13]
Need to migrate this stuff: http://yepdesign.co.uk/clients/ou/ice/4/drupal.php

We shouldn't have a page called Drupal specifics, Wordpress specifics or Kentico specifics. If we develop bits of interface as a result of a need that originates from a CMS then it is likely to be useful to other CMSes too. If these CMSes wont allow you to change the HTML then we need to provide alternative code along with the original. Saying - this is how you do it normally, but this is what you need for Drupal.

**Comment by sleicester** [comment]
This issue was moved to the-open-university/ouice#13
