### ISSUE TITLE
Sort out the branch organisation

### ISSUE THREAD

**Issue by guyweb** [the-open-university/student-theme-framework#15]
Currently we have two main branches:

1. Master - contains the theme assets only
2. gh-pages - contains the theme assets and a demo site.

I propose that we always bundle everything together in a branch. Something like:

[public] - for the deployable assets.
[examples] - for the demo site.
[tools] - for integrating with stuff.

Discuss.

**Comment by sleicester** [comment]
This issue was moved to the-open-university/ouice#15
