### ISSUE TITLE
Make demo site work under "HTTPS"...

### ISSUE THREAD

**Issue by nfreear** [the-open-university/student-theme-framework#18]
It seems partly a matter of chance as to whether you end up at - `HTTP` - working:

* http://the-open-university.github.io/student-theme-framework/media.html

...Or, `HTTPS` - jQuery on Google CDN & `<object>` links broken (requested via `HTTP`):

* https://the-open-university.github.io/student-theme-framework/media.html

**Comment by sleicester** [comment]
This issue was moved to the-open-university/ouice#18
