### ISSUE TITLE
Log of sites that use this framework

### ISSUE THREAD

**Issue by stephenturvey** [the-open-university/student-theme-framework#20]
It would be ideal if there could exist somewhere a log of all the sites that use this framework. That way we can do compliance checks, ensure future changes we make ripple through nicely, etc. How can we achieve this? People submit a form when they put a site live? Slightly different but related: Do all or some of us need to check new sites before they go live?

**Comment by sleicester** [comment]
This issue was moved to the-open-university/ouice#20
