### ISSUE TITLE
Standardise navigation classes to just ou-nav

### ISSUE THREAD

**Issue by sleicester** [the-open-university/student-theme-framework#26]
Do we need the separate classes for navigation here:
http://the-open-university.github.io/student-theme-framework/navigation-context-nav.html

Why can't we just have one class and structure that's adaptive to the depth.

**Comment by sleicester** [comment]
Basically it causes a lot of work deciding on whether you have a nested menu or not just to set a class. I don't see the value of it.

**Comment by guyweb** [comment]
Can the same visual output be achieved without the class? If so, then worth a further chat. Also, remember that STF / OUICE is agnostic to CMS or other tech. The Drupal implementation etc may not be able to use the same HTML etc and that's ok. But we wouldn't change the framework based on the backend limitations necessarily. To be backward compatible we would need to keep this in our framework.

**Comment by sleicester** [comment]
This is agnostic!

The classes are kind of redundant, exactly the same markup for each type, except that with the context nav you may have a h2 in there.

**Comment by guyweb** [comment]
Maybe I don't appreciate the issue.

**Comment by sleicester** [comment]
Sneak a peak at the code I just committed.

**Comment by stephenturvey** [comment]
I'd like to refactor the majority of that CSS.

**Comment by sleicester** [comment]
This issue was moved to the-open-university/ouice#26
