### ISSUE TITLE
Text legibility / readability / accessibility

### ISSUE THREAD

**Issue by guyweb** [the-open-university/student-theme-framework#7]
Has the text used in the public prospectus been checked for legibility / readability / accessibility?

Since we are making something that needs to be usable across the student environment we need to be very hot on accessibility. 

Here's a screen showing the current public style on the left with a basic attempt to use the fonts Stephen has suggested on the right:

https://www.dropbox.com/s/17wap7kwhqj69g0/text.png?dl=0

**Comment by sleicester** [comment]
This issue was moved to the-open-university/ouice#7
