### ISSUE TITLE
Headers and footers

### ISSUE THREAD

**Issue by guyweb** [the-open-university/student-theme-framework#8]
We are waiting for the latest official headers and footers.

Next steps:

1. Digital engagement provide the spec for what links need to appear in the headers and footers.
2. Draft designs, by an actual designer, of the headers and footers.
3. Sign off designs by the working group.
4. Build responsive headers and footers.
5. Deploy headers and footers to /includes/ on all servers.
6. Update this repository.

**Comment by sleicester** [comment]
This issue was moved to the-open-university/ouice#8
