### ISSUE TITLE
Search box styling

### ISSUE THREAD

**Issue by guyweb** [the-open-university/student-theme-framework#9]
Keren Mills in the library writes: 

One thing that concerns me is the reddy/brown colour of the search boxes – it’s the sort of colour that usually signifies something to be cautious of, so it makes the search boxes look not very welcoming. It’s fine on the live help centre where it’s just the border of the search box, but on the experimental design the box background and search button pick up the colour and it sort of rings subconscious alarm bells.

**Comment by sleicester** [comment]
This issue was moved to the-open-university/ouice#9
